# -*- coding: utf-8 -*-
"""EXPOSICION_MINERIA_DATOS_CLUSTER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1df4udzhz826cI53HWxRWCiZSFseeK-oK
"""

# ==============================================================================
# 1. CARGA DE DATOS DESDE EXCEL Y CONSOLIDACIÓN DE MUNICIPIOS
# ==============================================================================
import pandas as pd
import numpy as np

# Cargar el archivo original de Excel (.xlsx)
# Asegúrate de subirlo a Google Colab con este nombre exacto
df_original = pd.read_excel('AFECTACIÓN A LA FUERZA PÚBLICA.xlsx', header=0)

# Columnas identificadoras
index_cols = ['COD_MUNI', 'MUNICIPIO', 'DEPARTAMENTO']

# Pivotamos las variables categóricas para convertirlas en conteos numéricos por municipio
pivot_accion = df_original.pivot_table(index=index_cols, columns='ACCION', values='CANTIDAD', aggfunc='sum', fill_value=0)
pivot_fuerza = df_original.pivot_table(index=index_cols, columns='NOMBRE_FUERZA', values='CANTIDAD', aggfunc='sum', fill_value=0)
pivot_cat = df_original.pivot_table(index=index_cols, columns='CATEGORIA', values='CANTIDAD', aggfunc='sum', fill_value=0)
total_municipio = df_original.groupby(index_cols)['CANTIDAD'].sum().to_frame(name='TOTAL_AFECTADOS')

# Unimos todo para crear la base consolidada de 884 municipios y sus nuevas variables numéricas
datos = total_municipio.join([pivot_accion, pivot_fuerza, pivot_cat]).reset_index()

# Renombramos temporalmente el identificador principal a 'State' para acoplarnos al código de la profesora
datos = datos.rename(columns={'MUNICIPIO': 'State'})

print(f"¡Base de datos preparada desde Excel! Filas (Municipios): {datos.shape[0]} | Columnas: {datos.shape[1]}")
print("\nPrimeras filas del análisis exploratorio:")
datos.head(n=10)

# ==============================================================================
# 2. DESCRIPCIÓN Y LIMPIEZA
# ==============================================================================
print(datos.describe())

# Eliminar cualquier valor faltante que pueda estar presente
datos = datos.dropna()
datos.info()

# ==============================================================================
# 3. HISTOGRAMAS DE VARIABLES CLAVE (ORIGINALES)
# ==============================================================================
import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(16, 5))

# Histograma TOTAL_AFECTADOS
plt.subplot(1, 4, 1)
sns.histplot(datos["TOTAL_AFECTADOS"], bins=15, kde=True, color='blue')
plt.title('TOTAL_AFECTADOS Original')

# Histograma ASESINADO
plt.subplot(1, 4, 2)
sns.histplot(datos['ASESINADO'], bins=15, kde=True, color='green')
plt.title('ASESINADO Original')

# Histograma HERIDO
plt.subplot(1, 4, 3)
sns.histplot(datos['HERIDO'], bins=15, kde=True, color='red')
plt.title('HERIDO Original')

# Histograma EJERCITO
plt.subplot(1, 4, 4)
sns.histplot(datos['EJERCITO NACIONAL DE COLOMBIA'], bins=15, kde=True, color='purple')
plt.title('EJÉRCITO Original')

plt.tight_layout()
plt.show()

# ==============================================================================
# 4. ESTANDARIZACIÓN (StandardScaler)
# ==============================================================================
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Seleccionar solo las columnas numéricas que usará el modelo (omitimos códigos y nombres)
columnas_omitir = ['COD_MUNI', 'State', 'DEPARTAMENTO']
numericas = [col for col in datos.columns if col not in columnas_omitir]

# Guardamos una copia sin escalar para los Boxplots posteriores
datos_originales_num = datos.copy()

# Estandarizar las columnas numéricas
datos[numericas] = scaler.fit_transform(datos[numericas])

print("Primeras filas estandarizadas:")
datos.head(10)

# ==============================================================================
# 5. MATRICES DE DISTANCIA (EUCLIDEANA Y MANHATTAN) Y MAPAS DE CALOR
# ==============================================================================
from sklearn.metrics.pairwise import euclidean_distances
from scipy.spatial.distance import pdist, squareform

# Definir la matriz X eliminando los identificadores de texto
X_scaled = datos.drop(columns=columnas_omitir)

# --- Distancia Euclideana ---
distancias_eu = euclidean_distances(X_scaled)
dist_matrix_euclidean = pd.DataFrame(distancias_eu, index=datos['State'], columns=datos['State'])

print("Matriz Euclideana (Muestra 6x6):")
print(np.round(dist_matrix_euclidean.iloc[:6, :6], 2))

# --- Distancia Manhattan ---
dist_matrix_manhattan = pdist(X_scaled, metric='cityblock')
C = squareform(dist_matrix_manhattan)
dist_matrix_manhattan_square = pd.DataFrame(C, index=datos['State'], columns=datos['State'])

print("\nMatriz Manhattan (Muestra 6x6):")
print(np.round(dist_matrix_manhattan_square.iloc[:6, :6], 2))

# --- Gráficos de Mapas de Calor ---
fig, ax = plt.subplots(1, 2, figsize=(20, 8))

sns.heatmap(dist_matrix_euclidean, linewidth=.05, cmap='coolwarm', annot=False, ax=ax[0])
ax[0].set_title('Matriz de Distancias Euclidianas (884 Municipios)', fontsize=14)

sns.heatmap(dist_matrix_manhattan_square, linewidth=.05, cmap='coolwarm', annot=False, ax=ax[1])
ax[1].set_title('Matriz de Distancias Manhattan (884 Municipios)', fontsize=14)

plt.show()

# ==============================================================================
# 6. MÉTODO DEL CODO (ELBOW METHOD)
# ==============================================================================
from sklearn.cluster import KMeans

wss = []

# Calcular WSS para K de 1 a 10
for k in range(1, 11):
    kmeans = KMeans(n_clusters=k, n_init=50, random_state=42)
    kmeans.fit(X_scaled)
    wss.append(kmeans.inertia_)

print("La suma total de cuadrados intra-cluster (inertia) son:\n", wss)

# Graficar el método del codo
plt.figure(figsize=(8, 6))
plt.plot(range(1, 11), wss, marker='o', color='green', linestyle='-')
plt.title('Método del Codo (Elbow Method)', fontsize=19, color="red")
plt.xlabel('Número de Clústeres', fontsize=12)
plt.ylabel('Suma total de cuadrados intra-cluster (WSS)', fontsize=12)

# Añadimos la línea vertical en k=4 (Ajustable según necesidad)
plt.axvline(x=4, color='blue', linestyle='--', linewidth=2)
plt.grid(True)
plt.show()

# ==============================================================================
# 7. EJECUCIÓN DEL ALGORITMO K-MEANS CON K=4
# ==============================================================================
import time

random_seed = 42
kmeans = KMeans(n_clusters=4, n_init=50, random_state=random_seed)

# Ajustar modelo
start = time.time()
km4_clusters = kmeans.fit(X_scaled)
print("KMEANS tomó: %.2f ms" % ((time.time() - start)*1000))

print("\nCentroides (coordenadas escaladas):\n", km4_clusters.cluster_centers_)
print("\nEtiquetas de los clústers asignados a los primeros 20 municipios:\n", km4_clusters.labels_[:20])
print("\nInercia Total (WSS final):", km4_clusters.inertia_)

# ==============================================================================
# 8. REDUCCIÓN DIMENSIONAL (PCA) Y VISUALIZACIÓN CON ELIPSES
# ==============================================================================
from sklearn.decomposition import PCA
from matplotlib.patches import Ellipse

pca = PCA(n_components=2)
datos_pca = pca.fit_transform(X_scaled)

# Construir DataFrame de visualización
datos_pca_df = pd.DataFrame(data=datos_pca, columns=['PCA1', 'PCA2'])
datos_pca_df['Cluster'] = km4_clusters.labels_

plt.figure(figsize=(14, 10))
colores = ['red', 'green', 'blue', 'yellow']

# Dibujar Municipios
sns.scatterplot(x='PCA1', y='PCA2', hue='Cluster', data=datos_pca_df, palette=colores, s=40, alpha=0.7)

# Dibujar Centroides
centroids_pca = pca.transform(kmeans.cluster_centers_)
plt.scatter(centroids_pca[:, 0], centroids_pca[:, 1], s=400, c=colores, marker='*', edgecolor='black', label='Centroides')

# Dibujar las elipses de covarianza por grupo
for i, color in enumerate(colores):
    cluster_points = datos_pca_df[datos_pca_df['Cluster'] == i][['PCA1', 'PCA2']]
    if len(cluster_points) > 1:
        cov = np.cov(cluster_points, rowvar=False)
        eigenvalues, eigenvectors = np.linalg.eigh(cov)
        angle = np.degrees(np.arctan2(eigenvectors[1, 0], eigenvectors[0, 0]))
        width, height = 2 * np.sqrt(eigenvalues) * 2  # Multiplicador de escala de elipse
        ellipse = Ellipse(xy=centroids_pca[i], width=width, height=height, angle=angle, color=color, alpha=0.15)
        plt.gca().add_patch(ellipse)

# Adicionar textos de nombres (colocamos muestra aleatoria de municipios para evitar saturación de texto)
for i, row in datos_pca_df.iterrows():
    if i % 15 == 0:  # Muestra texto cada 15 filas para que sea legible en los 884 registros
        plt.text(row['PCA1'], row['PCA2'] + 0.05, datos['State'][i], fontsize=7, ha='center', alpha=0.8)

plt.title('Algoritmo K-means con clusters k=4 y Elipses (Municipios Colombianos)', fontsize=18)
plt.xlabel('PCA1', fontsize=12)
plt.ylabel('PCA2', fontsize=12)
plt.text(datos_pca_df['PCA1'].max()-2, datos_pca_df['PCA2'].min(), "Inercia = %0.2f" % km4_clusters.inertia_, fontsize=14, bbox=dict(facecolor='white', alpha=0.5))
plt.legend()
plt.grid(True)
plt.show()

# ==============================================================================
# 9. CANTIDAD DE MUNICIPIOS POR CLÚSTER
# ==============================================================================
G = pd.DataFrame()
G['State'] = datos['State'].values
G['DEPARTAMENTO'] = datos['DEPARTAMENTO'].values
G['label'] = km4_clusters.labels_

cantidadGrupo = pd.DataFrame(index=range(4))
cantidadGrupo['color'] = colores
cantidadGrupo['cantidad_individuos'] = G.groupby('label').size()
print(cantidadGrupo)

print("\nListado ordenado de municipios por grupo (Muestra de los primeros 15):")
print(G.sort_values(by='label').head(15).to_string(index=False))

# ==============================================================================
# 10. VISUALIZACIÓN CRUZANDO VARIABLES CLAVE (TOTAL_AFECTADOS vs ASESINADO)
# ==============================================================================
# Usamos las posiciones del arreglo original indexado
f1 = datos['TOTAL_AFECTADOS'].values
f2 = datos['ASESINADO'].values

asignar = [colores[row] for row in km4_clusters.labels_]

plt.figure(figsize=(10, 7))
plt.scatter(f1, f2, c=asignar, s=50, alpha=0.7)
plt.scatter(km4_clusters.cluster_centers_[:, 0], km4_clusters.cluster_centers_[:, 1], marker='*', c=colores, s=400, edgecolor='black', label='Centroides')
plt.title('TOTAL_AFECTADOS vs ASESINADO', fontsize=18)
plt.xlabel('TOTAL_AFECTADOS (Estandarizado)', fontsize=12)
plt.ylabel('ASESINADO (Estandarizado)', fontsize=12)
plt.grid(True)
plt.show()

# ==============================================================================
# 11. BOXPLOT DE LA DISTRIBUCIÓN POR GRUPO
# ==============================================================================
# Agregamos la etiqueta de clúster a los datos originales para que los valores del gráfico sean reales y no estandarizados
datos_originales_num['Cluster'] = km4_clusters.labels_

plt.figure(figsize=(10, 6))
sns.boxplot(x='Cluster', y='TOTAL_AFECTADOS', data=datos_originales_num, hue='Cluster', palette="Set1", dodge=False)
plt.xlabel('Clúster')
plt.ylabel('Cantidad Total Reales de Afectados')
plt.title('Distribución del Impacto Total por Clúster de Municipios')
plt.show()

# ==============================================================================
# 12. PCA INTERACTIVO EN 2D Y 3D CON PLOTLY EXPRESS
# ==============================================================================
import plotly.express as px
import plotly.graph_objects as go

pca_4d = PCA(n_components=4)
pca_scores_4d = pca_4d.fit_transform(X_scaled)

pca_df = pd.DataFrame(pca_scores_4d, columns=['PC1', 'PC2', 'PC3', 'PC4'])
pca_df['Cluster'] = km4_clusters.labels_.astype(str)
pca_df['Etiqueta'] = datos['State'] + " (" + datos['DEPARTAMENTO'] + ")"

# --- Gráfico Interactivo 2D ---
fig_2d = px.scatter(pca_df, x='PC1', y='PC2', color='Cluster', text='Etiqueta',
                    title='Visualización PCA Interactiva en 2D (Pasa el cursor sobre los municipios)',
                    labels={'PC1': 'Componente Principal 1', 'PC2': 'Componente Principal 2'},
                    template='plotly')
fig_2d.update_traces(textposition='top center', textfont_size=9)
fig_2d.update_layout(width=1200, height=700)
fig_2d.show()

# --- Gráfico Interactivo 3D ---
fig_3d = px.scatter_3d(pca_df, x='PC1', y='PC2', z='PC3', color='Cluster', hover_name='Etiqueta',
                       title='Visualización PCA Interactiva en 3D de tus Municipios',
                       labels={'PC1': 'PC1', 'PC2': 'PC2', 'PC3': 'PC3'},
                       template='plotly')

# Proyectar centroides al espacio 3D
centroids_pca_3d = pca_4d.transform(kmeans.cluster_centers_)

fig_3d.add_trace(go.Scatter3d(x=centroids_pca_3d[:, 0], y=centroids_pca_3d[:, 1], z=centroids_pca_3d[:, 2],
                              mode='markers',
                              marker=dict(size=12, color='black', symbol='diamond'),
                              name='Centroides'))

fig_3d.update_layout(width=1200, height=800)
fig_3d.show()

